import uuid
from typing import List, Optional
from datetime import datetime, date, timedelta
from fastapi import APIRouter, Depends, HTTPException, Query, status, Request
from sqlalchemy.orm import Session
from backend.app.database import get_db
from backend.app.models import (
    AIAlert, Institution, Inspection, User, Notification
)
from backend.app.schemas.ai import AIAlertResponse, AlertAcknowledgeRequest
from backend.app.schemas.common import PaginatedResponse
from backend.app.api.deps import get_current_user, require_roles, record_audit_log

router = APIRouter(prefix="/ai-alerts", tags=["AI Alerts"])

def format_alert(a: AIAlert) -> AIAlertResponse:
    return AIAlertResponse(
        id=a.id,
        ai_analysis_id=a.ai_analysis_id,
        institution_id=a.institution_id,
        severity=a.severity,
        title=a.title,
        alert_summary=a.alert_summary,
        suggested_inspection_scope=a.suggested_inspection_scope,
        is_acknowledged=a.is_acknowledged,
        acknowledged_by=a.acknowledged_by,
        acknowledged_at=a.acknowledged_at,
        created_at=a.created_at,
        institution_name=a.institution.name if a.institution else None,
        institution_state=a.institution.state if a.institution else None,
        institution_district=a.institution.district if a.institution else None
    )

@router.get("", response_model=PaginatedResponse[AIAlertResponse])
def list_ai_alerts(
    institution_id: Optional[uuid.UUID] = None,
    severity: Optional[str] = None,
    is_acknowledged: Optional[bool] = None,
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Lists anomaly alerts generated by the automated monitoring engine."""
    query = db.query(AIAlert)

    if institution_id:
        query = query.filter(AIAlert.institution_id == institution_id)
    if severity:
        query = query.filter(AIAlert.severity == severity.upper())
    if is_acknowledged is not None:
        query = query.filter(AIAlert.is_acknowledged == is_acknowledged)

    total = query.count()
    offset = (page - 1) * page_size
    items = query.order_by(AIAlert.created_at.desc()).offset(offset).limit(page_size).all()

    return PaginatedResponse(
        total=total,
        page=page,
        page_size=page_size,
        items=[format_alert(i) for i in items]
    )

@router.get("/{id}", response_model=AIAlertResponse)
def get_ai_alert(id: uuid.UUID, db: Session = Depends(get_db)):
    """Retrieves specific AI alert."""
    alert = db.query(AIAlert).filter(AIAlert.id == id).first()
    if not alert:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AI Alert not found")
    return format_alert(alert)

@router.post("/{id}/acknowledge", response_model=AIAlertResponse)
def acknowledge_ai_alert(
    id: uuid.UUID,
    ack_data: AlertAcknowledgeRequest,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(["SUPER_ADMIN", "MINISTRY_OFFICIAL", "DISTRICT_OFFICER"]))
):
    """
    Official acknowledges an AI alert and optionally orders immediate inspection dispatch.
    """
    alert = db.query(AIAlert).filter(AIAlert.id == id).first()
    if not alert:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AI Alert not found")

    alert.is_acknowledged = True
    alert.acknowledged_by = current_user.id
    alert.acknowledged_at = datetime.utcnow()
    alert.updated_at = datetime.utcnow()

    # Optionally trigger inspection
    if ack_data.create_inspection:
        inst = alert.institution
        current_year = datetime.utcnow().year
        count_today = db.query(Inspection).count() + 1
        state_prefix = inst.state[:2].upper() if inst else "IN"
        code = f"INSP-{current_year}-{state_prefix}-{count_today:04d}"

        inspection = Inspection(
            id=uuid.uuid4(),
            inspection_code=code,
            institution_id=alert.institution_id,
            origin_ai_alert_id=alert.id,
            priority=ack_data.priority or "URGENT",
            status="PENDING_DISPATCH",
            mandated_date=date.today(),
            due_date=date.today() + timedelta(days=2),
            inspection_reason=f"Mandated following AI Alert: {alert.title}. Scope: {alert.suggested_inspection_scope or 'General inspection'}",
            special_instructions=ack_data.action_note,
            assigned_by_user_id=current_user.id
        )
        db.add(inspection)

    db.commit()
    db.refresh(alert)

    record_audit_log(
        db, current_user, "AI_ALERT_ACKNOWLEDGED", "ai_alerts", alert.id,
        {"create_inspection": ack_data.create_inspection, "note": ack_data.action_note}, request
    )

    return format_alert(alert)
