"""
DRISHTI AI Engine: Deterministic Synthetic Data Generator
Domain: Ministry of Social Justice and Empowerment (MoSJE) - SIH 2026
Schemes Monitored: DDRS, AVYAY, NAPDDR, PM-DAKSH

All data generated by this module is purely SYNTHETIC demonstration data
crafted for mathematical modeling, pipeline verification, and algorithmic benchmarking.
NO real personal or institutional data is utilized.
"""

from typing import List, Dict, Any, Tuple
import datetime
import numpy as np
import pandas as pd

# Flagship Schemes under MoSJE Jurisdiction
SCHEMES = ["DDRS", "AVYAY", "NAPDDR", "PM-DAKSH"]

# Geographies for regional diversity
REGIONS = [
    ("Uttar Pradesh", "Varanasi"),
    ("Uttar Pradesh", "Lucknow"),
    ("Maharashtra", "Pune"),
    ("Maharashtra", "Nagpur"),
    ("Bihar", "Patna"),
    ("Rajasthan", "Jaipur"),
    ("Karnataka", "Bengaluru"),
    ("Tamil Nadu", "Chennai"),
    ("Madhya Pradesh", "Bhopal"),
    ("West Bengal", "Kolkata")
]

INSTITUTION_TYPES = ["SPECIAL_SCHOOL", "DE_ADDICTION_CENTRE", "SENIOR_CITIZEN_HOME", "SKILL_TRAINING_CENTRE"]

def generate_institution_profiles(n_institutions: int = 50, seed: int = 42) -> pd.DataFrame:
    """
    Generates a deterministic set of synthetic institutional baseline profiles.
    """
    rng = np.random.RandomState(seed)
    records = []

    for i in range(1, n_institutions + 1):
        inst_id = f"INST-SYNTH-{i:03d}"
        scheme = rng.choice(SCHEMES)
        inst_type = rng.choice(INSTITUTION_TYPES)
        state, district = REGIONS[rng.choice(len(REGIONS))]
        capacity = int(rng.choice([30, 40, 50, 60, 75, 100, 120, 150]))
        base_occupancy_rate = float(rng.uniform(0.70, 0.95))
        base_occupancy = int(round(capacity * base_occupancy_rate))

        # Assign synthetic profile behavioral archetype
        # ~74% Normal compliant, ~8% Attendance Flatline, ~6% Biometric mismatch,
        # ~6% Meal inflation, ~6% Multi-factor severe divergence
        profile_roll = rng.uniform(0, 100)
        if profile_roll < 74:
            archetype = "NORMAL_COMPLIANT"
        elif profile_roll < 82:
            archetype = "ATTENDANCE_FLATLINE"
        elif profile_roll < 88:
            archetype = "BIOMETRIC_MISMATCH"
        elif profile_roll < 94:
            archetype = "MEAL_INFLATION"
        else:
            archetype = "MULTI_FACTOR_DIVERGENCE"

        records.append({
            "institution_id": inst_id,
            "institution_name": f"MoSJE Demo Facility {i} ({scheme})",
            "scheme_code": scheme,
            "institution_type": inst_type,
            "state": state,
            "district": district,
            "registered_capacity": capacity,
            "expected_beneficiaries": base_occupancy,
            "archetype": archetype,
            "previous_inspection_score": round(float(rng.uniform(65.0, 95.0) if archetype == "NORMAL_COMPLIANT" else rng.uniform(35.0, 70.0)), 1),
            "inspection_frequency": int(rng.randint(1, 5)),
            "days_since_last_inspection": int(rng.randint(15, 180))
        })

    return pd.DataFrame(records)

def generate_synthetic_telemetry(
    n_institutions: int = 50,
    days_per_institution: int = 30,
    seed: int = 42,
    base_date: datetime.date = None
) -> pd.DataFrame:
    """
    Generates deterministic daily operational telemetry time-series for synthetic institutions.
    """
    if base_date is None:
        base_date = datetime.date(2026, 8, 1)

    rng = np.random.RandomState(seed)
    profiles_df = generate_institution_profiles(n_institutions=n_institutions, seed=seed)
    telemetry_rows = []

    for _, inst in profiles_df.iterrows():
        inst_id = inst["institution_id"]
        capacity = inst["registered_capacity"]
        expected = inst["expected_beneficiaries"]
        archetype = inst["archetype"]
        prev_score = inst["previous_inspection_score"]

        for day in range(days_per_institution):
            current_date = base_date + datetime.timedelta(days=day)
            is_weekend = current_date.weekday() in (5, 6)

            # Generate signals based on profile archetype
            if archetype == "NORMAL_COMPLIANT":
                # Healthy operational variance
                att_ratio = rng.normal(0.88, 0.04)
                att_ratio = np.clip(att_ratio, 0.65, 0.98)
                attendance = int(round(expected * att_ratio))

                # Biometric punches closely track attendance with 1-3% hardware slip
                bio_ratio = rng.uniform(0.92, 0.99)
                biometric_punch = int(round(attendance * bio_ratio))

                # Meals 2 per resident beneficiary
                meals_per_ben = 2
                expected_meals = attendance * meals_per_ben
                meals_served = int(round(expected_meals * rng.normal(1.0, 0.03)))

                cctv_uptime = float(np.clip(rng.normal(96.0, 2.5), 85.0, 100.0))
                occupancy = int(round(attendance * rng.uniform(1.0, 1.05)))
                occupancy = min(occupancy, capacity)
                roster_discrepancy = int(rng.choice([0, 0, 1, 0, 2]))
                geofence_offset = float(max(2.0, rng.normal(18.0, 8.0)))
                inspection_delay = max(0, int(inst["days_since_last_inspection"] - 90))
                is_anomaly_label = False
                anomaly_type = "NONE"

            elif archetype == "ATTENDANCE_FLATLINE":
                # Artificial 100% flatline across every day including weekends
                attendance = expected
                biometric_punch = expected
                meals_served = expected * 2
                expected_meals = expected * 2
                cctv_uptime = 98.0
                occupancy = expected
                roster_discrepancy = 0
                geofence_offset = 12.0
                inspection_delay = max(0, int(inst["days_since_last_inspection"] - 90))
                is_anomaly_label = True
                anomaly_type = "ATTENDANCE_FLATLINE"

            elif archetype == "BIOMETRIC_MISMATCH":
                # High claimed attendance but very low biometric verification
                attendance = int(round(expected * rng.uniform(0.90, 0.98)))
                biometric_punch = int(round(attendance * rng.uniform(0.25, 0.50)))
                meals_served = attendance * 2
                expected_meals = attendance * 2
                cctv_uptime = float(rng.uniform(70.0, 85.0))
                occupancy = attendance
                roster_discrepancy = int(rng.randint(4, 12))
                geofence_offset = float(rng.uniform(40.0, 120.0))
                inspection_delay = int(rng.randint(20, 75))
                is_anomaly_label = True
                anomaly_type = "BIOMETRIC_MISMATCH"

            elif archetype == "MEAL_INFLATION":
                # Claimed meals significantly exceed physical headcount
                attendance = int(round(expected * rng.uniform(0.60, 0.75)))
                biometric_punch = int(round(attendance * rng.uniform(0.85, 0.95)))
                # Claiming meals for 100% capacity + extra
                expected_meals = attendance * 2
                meals_served = int(round(capacity * 2 * rng.uniform(1.1, 1.35)))
                cctv_uptime = float(rng.uniform(80.0, 95.0))
                occupancy = attendance
                roster_discrepancy = int(rng.randint(5, 15))
                geofence_offset = float(rng.uniform(15.0, 45.0))
                inspection_delay = int(rng.randint(10, 45))
                is_anomaly_label = True
                anomaly_type = "MEAL_INFLATION"

            else:  # MULTI_FACTOR_DIVERGENCE
                # Extreme divergence across attendance, CCTV, geofence, and roster
                attendance = int(round(expected * rng.uniform(0.35, 0.60)))
                biometric_punch = int(round(attendance * rng.uniform(0.20, 0.45)))
                expected_meals = attendance * 2
                meals_served = int(round(capacity * 2 * rng.uniform(1.2, 1.4)))
                cctv_uptime = float(rng.uniform(20.0, 55.0))
                occupancy = attendance
                roster_discrepancy = int(rng.randint(10, 25))
                geofence_offset = float(rng.uniform(250.0, 600.0))
                inspection_delay = int(rng.randint(60, 150))
                is_anomaly_label = True
                anomaly_type = "MULTI_FACTOR_DIVERGENCE"

            telemetry_rows.append({
                "institution_id": inst_id,
                "institution_name": inst["institution_name"],
                "scheme_code": inst["scheme_code"],
                "date": current_date.isoformat(),
                "registered_capacity": capacity,
                "expected_beneficiaries": expected,
                "attendance_count": attendance,
                "biometric_punch_count": biometric_punch,
                "cctv_uptime_percentage": round(cctv_uptime, 1),
                "occupancy": occupancy,
                "meals_served": meals_served,
                "expected_meals": expected_meals,
                "roster_discrepancy": roster_discrepancy,
                "geofence_offset_meters": round(geofence_offset, 1),
                "inspection_frequency": inst["inspection_frequency"],
                "previous_inspection_score": prev_score,
                "inspection_delay": inspection_delay,
                "is_synthetic_label": is_anomaly_label,
                "anomaly_pattern": anomaly_type
            })

    df = pd.DataFrame(telemetry_rows)
    return df

def generate_benchmark_dataset(seed: int = 42) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Generates standard train and test synthetic datasets with fixed random seeds.
    Training set contains 60 institutions (1,800 daily records).
    Test evaluation set contains 20 distinct institutions (600 daily records).
    """
    train_df = generate_synthetic_telemetry(n_institutions=60, days_per_institution=30, seed=seed)
    test_df = generate_synthetic_telemetry(n_institutions=20, days_per_institution=30, seed=seed + 999)
    return train_df, test_df

if __name__ == "__main__":
    df = generate_synthetic_telemetry(n_institutions=5, days_per_institution=7)
    print("Generated Synthetic Telemetry Sample:")
    print(f"Total Rows: {len(df)}")
    print(f"Columns: {list(df.columns)}")
    print(df.head(3))
